name: CI Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip' # Ускоряет повторные сборки за счет кэширования пакетов

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем фреймворк тестирования и линтер
        pip install pytest flake8
        # opencv-python-headless критичен для CI, так как на серверах GitHub нет графического экрана
        pip install ultralytics opencv-python-headless numpy

    - name: Lint with flake8
      run: |
        # Быстрая проверка синтаксиса (вызовет ошибку сборки, если код сломан)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests with pytest
      run: |
        # Запуск тестов. Флаг -v выведет детальный отчет по каждому тесту.
        pytest -v
